### ISSUE TITLE
Some kind of frontend bug

### ISSUE THREAD

**Issue by gladuo** [ericls/niji#23] opened 2016-07-31 06:08 UTC
![image](https://cloud.githubusercontent.com/assets/5893628/17274903/dfdcd872-5727-11e6-8904-2395e3b6e220.png)

Some kind of frontend bug.
I enjoy your nice work and will be willing to contribute some code for this project.

**Comment by ericls** [comment] 2016-08-03 04:35
I cannot reproduce this bug.

However, the current implementation uses Bootstrap's row and col, which is not as clear as  [Bootstrap's media object](http://getbootstrap.com/components/#media).

So, I'm considering switching to the latter, and this bug should be automatically fixed with a `max-width`. 

PS: I have no proficiency in UI (CSS, HTML). Please correct me if I'm wrong.

**Comment by gladuo** [comment] 2016-08-03 14:10
I use Chrome 51 under macos.
I would give you a suggestion like...
![image](https://cloud.githubusercontent.com/assets/5893628/17368514/efef9cf8-59c6-11e6-95ee-08c55db097e5.png)
Hope to use your project soon. lol

**Comment by ericls** [comment] 2016-08-07 05:08
@gladuo Sorry I haven't fix this after 4 days. I'm kinda busy making up the tests recently. Can you please try to fix this and make a pull request? 

As you can see, i'm planning on release this APP (0.1.0) and there's lots of work to be done, can we collaborate on some of the related issues?

**Comment by ericls** [comment] 2016-08-08 05:21
Fixed with 43f9d5d012815a192ea233e52db2d2390ed4b0d9

**Closed by ericls** 2016-08-08 05:21 UTC
Labels: bug
